version: '3.8'

services:
  kali-gui:
    container_name: kali-gui
    build:
      context: .
    ports:
      - "6080:6080"        # noVNC web access
    network_mode: host
    restart: unless-stopped
    environment:
      - USER=root
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
    volumes:
      - ./data:/root/data  # Optional shared folder
    tty: true

